php7:
  build: .
  dockerfile: ./etc/docker/dockerfile_php_7
  volumes:
    - ./sites:/var/www/html
    - ./etc/php:/usr/local/etc/php
    - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
    - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
  ports:
    - "81:80"
    - "8081:8080"
  links:
    - mysql


mysql:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  ports:
    - "3306:3306"
    - "33060:33060"
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=edge     
  volumes:
    - ./etc/mysql:/docker-entrypoint-initdb.d
